version: '3.8'
services:
  backend:
    build:
      context: ./Backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - ./Backend:/app
    restart: unless-stopped
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
volumes:
  mongo-data: 